export const movies = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/the-up-files-.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/the-up-files-.jpg",
    about1: "The Up Files",
    about2: "Drama/Political",
    about3: "",
    lang: ["Hindi", "English", "Tamil"],
    genre: ["Drama", "Political"],
    dates: "Today",
    about:
      "The Up Files is a gripping political drama that delves into the intricate world of Indian politics. Set against the backdrop of a high-stakes election, the film follows the journey of an idealistic young politician as they navigate through corruption, power struggles, and moral dilemmas. With its stellar cast and thought-provoking narrative, The Up Files offers a compelling look at the challenges and complexities of modern democracy.",
    duration: "2h 30min",
    location: "PVR Cinemas, Select Citywalk, New Delhi",
    dateRange: "August 17, 2024 - September 30, 2024",
    screeningTypes: ["2D", "IMAX"],
    certification: "U/A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00391654-1720678873.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00391654-1720678873.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+1",
      "https://via.placeholder.com/120x120.png?text=Actor+2",
      "https://via.placeholder.com/120x120.png?text=Actor+3",
      "https://via.placeholder.com/120x120.png?text=Actor+4",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-image,i-discovery-catalog@@icons@@star-icon-202203010609.png,lx-24,ly-615,w-29,l-end:l-text,ie-OC44LzEwICA2NS43SyBWb3Rlcw%3D%3D,fs-29,co-FFFFFF,ly-612,lx-70,pa-8_0_0_0,l-end/et00341295-zqptbekxaj-portrait.jpg",
    about1: "Deadpool & Wolverine",
    about2: "Action/Adventure/Comedy",
    about3: "",
    lang: ["English", "Hindi", "Telugu", "Tamil"],
    genre: ["Action", "Adventure", "Comedy"],
    dates: "Today",
    about:
      "Deadpool & Wolverine brings together two of Marvel's most beloved anti-heroes in an action-packed, hilarious adventure. Wade Wilson's Deadpool joins forces with Logan's Wolverine, combining witty banter with intense combat sequences. As they face a common enemy, the duo must overcome their differences and work together, resulting in unexpected comedy and thrilling action scenes that will keep audiences on the edge of their seats.",
    duration: "2h 15min",
    location: "INOX, Nehru Place, New Delhi",
    dateRange: "August 17, 2024 - October 15, 2024",
    screeningTypes: ["2D", "3D", "4DX", "IMAX 3D"],
    certification: "A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-00341295-1718018322.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-00341295-1718018322.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+5",
      "https://via.placeholder.com/120x120.png?text=Actor+6",
      "https://via.placeholder.com/120x120.png?text=Actor+7",
      "https://via.placeholder.com/120x120.png?text=Actor+8",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-image,i-discovery-catalog@@icons@@star-icon-202203010609.png,lx-24,ly-615,w-29,l-end:l-text,ie-OS4xLzEwICA0OC4xSyBWb3Rlcw%3D%3D,fs-29,co-FFFFFF,ly-612,lx-70,pa-8_0_0_0,l-end/et00374797-kqytbtqgwb-portrait.jpg",
    about1: "Bad Newz",
    about2: "Comedy/Drama",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Comedy", "Drama"],
    dates: "Today",
    about:
      "Bad Newz is a rib-tickling comedy-drama that follows the misadventures of a dysfunctional family trying to keep their failing news channel afloat. As they stumble from one hilarious situation to another, the film explores themes of family bonds, media ethics, and the pursuit of truth in the age of fake news. With its clever writing and outstanding performances, Bad Newz delivers both laughs and poignant moments.",
    duration: "2h 10min",
    location: "Cinepolis, Unity One Mall, Rohini, Delhi",
    dateRange: "August 17, 2024 - September 20, 2024",
    screeningTypes: ["2D"],
    certification: "U/A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00391805-1721214274.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00391805-1721214274.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+9",
      "https://via.placeholder.com/120x120.png?text=Actor+10",
      "https://via.placeholder.com/120x120.png?text=Actor+11",
      "https://via.placeholder.com/120x120.png?text=Actor+12",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Kalki 2898D",
    about2: "Action/Sci-fi/Thriller",
    about3: "",
    lang: ["Hindi", "English", "Tamil", "Telugu", "Malayalam"],
    genre: ["Action", "Sci-fi", "Thriller"],
    dates: "Today",
    about:
      "Kalki 2898D is a futuristic sci-fi thriller set in a dystopian India. The film follows Kalki, a rebellious AI programmer, as she uncovers a sinister plot that threatens humanity's existence. With stunning visuals, mind-bending action sequences, and thought-provoking themes about technology and human nature, Kalki 2898D offers a unique blend of Indian mythology and cutting-edge science fiction.",
    duration: "2h 45min",
    location: "PVR, Pacific Mall, Subhash Nagar, New Delhi",
    dateRange: "August 17, 2024 - October 31, 2024",
    screeningTypes: ["2D", "3D", "IMAX 3D"],
    certification: "U/A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00352941-1718275859.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00352941-1718275859.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+13",
      "https://via.placeholder.com/120x120.png?text=Actor+14",
      "https://via.placeholder.com/120x120.png?text=Actor+15",
      "https://via.placeholder.com/120x120.png?text=Actor+16",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Twisters",
    about2: "Action/Adventure/Thriller",
    about3: "",
    lang: ["English", "Hindi", "Tamil", "Telugu"],
    genre: ["Action", "Adventure", "Thriller"],
    dates: "Today",
    about:
      "Twisters is a heart-pounding action-adventure that throws viewers into the eye of the storm. Following a team of daring storm chasers, the film showcases their dangerous pursuit of an unprecedented tornado outbreak across the Indian subcontinent. With state-of-the-art special effects and a gripping narrative about climate change and human resilience, Twisters offers an adrenaline-fueled cinematic experience.",
    duration: "2h 20min",
    location: "Carnival Cinemas, Eros One, Jangpura Extension, New Delhi",
    dateRange: "August 17, 2024 - September 30, 2024",
    screeningTypes: ["2D", "3D", "4DX"],
    certification: "U/A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00387070-1723539828.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00387070-1723539828.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+20",
      "https://via.placeholder.com/120x120.png?text=Actor+17",
      "https://via.placeholder.com/120x120.png?text=Actor+18",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Despicable Me 4",
    about2: "Action/Animation/Comedy",
    about3: "",
    lang: ["English", "Hindi", "Tamil", "Telugu"],
    genre: ["Animation", "Comedy", "Family"],
    dates: "Today",
    about:
      "Despicable Me 4 brings back the lovable Gru and his mischievous Minions for another hilarious adventure. This time, Gru faces his toughest challenge yet: parenthood. As he struggles to balance his family life with a new villainous threat, chaos and comedy ensue. With its signature blend of heart, humor, and outrageous action, Despicable Me 4 promises fun for the whole family.",
    duration: "1h 45min",
    location: "PVR, Vegas Mall, Dwarka, New Delhi",
    dateRange: "August 17, 2024 - October 15, 2024",
    screeningTypes: ["2D", "3D"],
    certification: "U",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00386901-1723182543.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00386901-1723182543.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+19",
      "https://via.placeholder.com/120x120.png?text=Actor+21",
      "https://via.placeholder.com/120x120.png?text=Actor+22",
      "https://via.placeholder.com/120x120.png?text=Actor+23",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Kill",
    about2: "Action/Thriller",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Action", "Thriller"],
    dates: "Today",
    about:
      "Kill is a high-octane action thriller that follows an elite assassin on her final mission before retirement. As she navigates through a web of deceit and danger, she uncovers a conspiracy that puts everything she cares about at risk. With intense fight sequences, unexpected plot twists, and a strong female lead, Kill delivers a pulse-pounding cinematic experience that will keep viewers on the edge of their seats.",
    duration: "2h 5min",
    location: "Cinepolis, DLF Avenue, Saket, New Delhi",
    dateRange: "August 17, 2024 - September 25, 2024",
    screeningTypes: ["2D"],
    certification: "A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+24",
      "https://via.placeholder.com/120x120.png?text=Actor+25",
      "https://via.placeholder.com/120x120.png?text=Actor+26",
      "https://via.placeholder.com/120x120.png?text=Actor+27",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Inside Out 2",
    about2: "Animation/Comedy/Drama",
    about3: "",
    lang: ["English", "Hindi", "Tamil", "Telugu"],
    genre: ["Animation", "Comedy", "Drama"],
    dates: "Today",
    about:
      "Inside Out 2 takes us back into the mind of Riley, now a teenager, as she navigates the complex emotions of adolescence. As new emotions join the team, including Anxiety and Embarrassment, Joy and the others must learn to work with these new feelings to help Riley through this challenging time. With its trademark blend of humor, heart, and psychological insight, Inside Out 2 offers a touching and hilarious look at growing up.",
    duration: "1h 55min",
    location: "PVR, Ambience Mall, Vasant Kunj, New Delhi",
    dateRange: "August 17, 2024 - October 20, 2024",
    screeningTypes: ["2D", "3D"],
    certification: "U",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+28",
      "https://via.placeholder.com/120x120.png?text=Actor+29",
      "https://via.placeholder.com/120x120.png?text=Actor+30",
      "https://via.placeholder.com/120x120.png?text=Actor+31",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Sarfira",
    about2: "Biography/Drama",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Biography", "Drama"],
    dates: "Today",
    about:
      "Sarfira is an inspiring biographical drama that tells the true story of Sarfira Kumari, a young woman from rural India who defied all odds to become a renowned space scientist. The film chronicles her journey from a small village to the Indian Space Research Organisation, highlighting her struggles, triumphs, and unwavering determination. With powerful performances and a motivational narrative, Sarfira celebrates the spirit of perseverance and the pursuit of dreams.",
    duration: "2h 40min",
    location: "INOX, Aishwarya Multiplex, Palam, New Delhi",
    dateRange: "August 17, 2024 - October 10, 2024",
    screeningTypes: ["2D"],
    certification: "U",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    releaseDate: "30 August, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+32",
      "https://via.placeholder.com/120x120.png?text=Actor+33",
      "https://via.placeholder.com/120x120.png?text=Actor+34",
      "https://via.placeholder.com/120x120.png?text=Actor+35",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Despicable Me 4",
    about2: "Action/Adventure/Animation/Comedy",
    about3: "",
    lang: ["Hindi", "English", "Tamil", "Telugu"],
    genre: ["Animation", "Comedy", "Family"],
    dates: "Today",
    about:
      "Despicable Me 4 brings back the lovable Gru and his mischievous Minions for another hilarious adventure. This time, Gru faces his toughest challenge yet: parenthood. As he struggles to balance his family life with a new villainous threat, chaos and comedy ensue.",
    duration: "1h 45min",
    location: "PVR, Vegas Mall, Dwarka, New Delhi",
    dateRange: "August 17, 2024 - October 15, 2024",
    screeningTypes: ["2D", "3D"],
    certification: "U",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+36",
      "https://via.placeholder.com/120x120.png?text=Actor+37",
      "https://via.placeholder.com/120x120.png?text=Actor+38",
      "https://via.placeholder.com/120x120.png?text=Actor+39",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Kill",
    about2: "Action/Thriller",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Action", "Thriller"],
    dates: "Today",
    about:
      "Kill is a high-octane action thriller that follows an elite assassin on her final mission before retirement. As she navigates through a web of deceit and danger, she uncovers a conspiracy that puts everything she cares about at risk.",
    duration: "2h 5min",
    location: "Cinepolis, DLF Avenue, Saket, New Delhi",
    dateRange: "August 17, 2024 - September 25, 2024",
    screeningTypes: ["2D"],
    certification: "A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+40",
      "https://via.placeholder.com/120x120.png?text=Actor+41",
      "https://via.placeholder.com/120x120.png?text=Actor+42",
      "https://via.placeholder.com/120x120.png?text=Actor+43",
      "https://via.placeholder.com/120x120.png?text=Actor+44",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Inside Out 2",
    about2: "Animation/Comedy/Drama",
    about3: "",
    lang: ["Hindi", "English", "Tamil", "Telugu"],
    genre: ["Animation", "Comedy", "Drama"],
    dates: "Today",
    about:
      "Inside Out 2 takes us back into the mind of Riley, now a teenager, as she navigates the complex emotions of adolescence. As new emotions join the team, including Anxiety and Embarrassment, Joy and the others must learn to work with these new feelings to help Riley through this challenging time.",
    duration: "1h 55min",
    location: "PVR, Ambience Mall, Vasant Kunj, New Delhi",
    dateRange: "August 17, 2024 - October 20, 2024",
    screeningTypes: ["2D", "3D"],
    certification: "U",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+40",
      "https://via.placeholder.com/120x120.png?text=Actor+41",
      "https://via.placeholder.com/120x120.png?text=Actor+42",
      "https://via.placeholder.com/120x120.png?text=Actor+43",
      "https://via.placeholder.com/120x120.png?text=Actor+44",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Sarfira",
    about2: "Biography/Drama",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Biography", "Drama"],
    dates: "Today",
    about:
      "Sarfira is an inspiring biographical drama that tells the true story of Sarfira Kumari, a young woman from rural India who defied all odds to become a renowned space scientist. The film chronicles her journey from a small village to the Indian Space Research Organisation, highlighting her struggles, triumphs, and unwavering determination.",
    duration: "2h 40min",
    location: "INOX, Aishwarya Multiplex, Palam, New Delhi",
    dateRange: "August 17, 2024 - October 10, 2024",
    screeningTypes: ["2D"],
    certification: "U",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+40",
      "https://via.placeholder.com/120x120.png?text=Actor+41",
      "https://via.placeholder.com/120x120.png?text=Actor+42",
      "https://via.placeholder.com/120x120.png?text=Actor+43",
      "https://via.placeholder.com/120x120.png?text=Actor+44",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "The Last Airbender",
    about2: "Action/Adventure/Fantasy",
    about3: "",
    lang: ["Hindi", "English", "Tamil", "Telugu"],
    genre: ["Action", "Adventure", "Fantasy"],
    dates: "Today",
    about:
      "Based on the beloved animated series, The Last Airbender brings the world of elemental bending to life in a live-action epic. Follow Aang, the young Avatar, as he masters the four elements and leads the fight against the oppressive Fire Nation.",
    duration: "2h 25min",
    location: "PVR, Select Citywalk, Saket, New Delhi",
    dateRange: "September 1, 2024 - November 15, 2024",
    screeningTypes: ["2D", "3D", "IMAX 3D"],
    certification: "UA",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+40",
      "https://via.placeholder.com/120x120.png?text=Actor+41",
      "https://via.placeholder.com/120x120.png?text=Actor+42",
      "https://via.placeholder.com/120x120.png?text=Actor+43",
      "https://via.placeholder.com/120x120.png?text=Actor+44",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Chandramukhi Returns",
    about2: "Horror/Thriller",
    about3: "",
    lang: ["Tamil", "Telugu", "Hindi"],
    genre: ["Horror", "Thriller"],
    dates: "Today",
    about:
      "The chilling sequel to the blockbuster Tamil horror film, Chandramukhi Returns brings back the terrifying ghost with a vengeance. As a new family moves into the haunted Vettaiyapuram mansion, they must uncover the truth behind Chandramukhi's curse before it's too late.",
    duration: "2h 35min",
    location: "Cinepolis, Unity One Mall, Rohini, Delhi",
    dateRange: "October 1, 2024 - November 30, 2024",
    screeningTypes: ["2D"],
    certification: "A",
    src2: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    bgImage:
      "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/deadpool-and-wolverine-et00308758-1710148891.jpg",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Actor+40",
      "https://via.placeholder.com/120x120.png?text=Actor+41",
      "https://via.placeholder.com/120x120.png?text=Actor+42",
      "https://via.placeholder.com/120x120.png?text=Actor+43",
      "https://via.placeholder.com/120x120.png?text=Actor+44",
    ],
  },
];
export const music = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "PokerBaazi Presents Hiten Panwar Live",
    about2: "Club Gigs",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Live Music", "Pop"],
    dates: "Today",
    about:
      "Experience the electrifying performance of Hiten Panwar, one of India's most talented young musicians, in this exclusive live gig presented by PokerBaazi. Known for his soulful voice and captivating stage presence, Hiten will take you on a musical journey through his latest hits and fan favorites. This intimate club setting provides the perfect atmosphere to enjoy Hiten's unique blend of contemporary and classical Indian music.",
    duration: "3h",
    location: "Playground, Sector 29, Gurugram",
    dateRange: "August 17, 2024 - August 17, 2024",
    screeningTypes: ["Live Performance"],
    certification: "A",
    releaseDate: "August 17, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Hiten+Panwar",
      "https://via.placeholder.com/120x120.png?text=Backing+Vocalist",
      "https://via.placeholder.com/120x120.png?text=Guitarist",
      "https://via.placeholder.com/120x120.png?text=Drummer",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Cigarettes After Sex X's India Tour 2025= Gurugram",
    about2: "Concerts",
    about3: "",
    lang: ["English"],
    genre: ["Indie", "Dream Pop"],
    dates: "Today",
    about:
      "Cigarettes After Sex brings their dreamy, atmospheric sound to Gurugram as part of their India Tour 2025. Known for their ethereal melodies and introspective lyrics, the band promises an unforgettable night of ambient pop. Fans can expect to hear favorites from their acclaimed albums, as well as new material, in an intimate and mesmerizing live performance.",
    duration: "2h 30min",
    location: "Backyard Sports Club, Sector 59, Gurugram",
    dateRange: "February 15, 2025 - February 15, 2025",
    screeningTypes: ["Live Concert"],
    certification: "A",
    releaseDate: "February 15, 2025",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Greg+Gonzalez",
      "https://via.placeholder.com/120x120.png?text=Randall+Miller",
      "https://via.placeholder.com/120x120.png?text=Jacob+Tomsky",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Sunburn Arena Ft. Alan Walker - Delhi NCR",
    about2: "Concerts",
    about3: "",
    lang: ["English"],
    genre: ["EDM", "Electronic"],
    dates: "Today",
    about:
      "Sunburn Arena brings the globally acclaimed DJ and producer Alan Walker to Delhi NCR for an electrifying night of electronic dance music. Known for his chart-topping hits like 'Faded' and 'Alone', Alan Walker will deliver a high-energy performance featuring his signature blend of EDM, pop, and cinematic sounds. This immersive audiovisual experience promises to be a highlight of Delhi's music calendar.",
    duration: "4h",
    location: "Jawaharlal Nehru Stadium, New Delhi",
    dateRange: "September 15, 2024 - September 15, 2024",
    screeningTypes: ["Live DJ Set"],
    certification: "A",
    releaseDate: "September 15, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Alan+Walker",
      "https://via.placeholder.com/120x120.png?text=Opening+Act",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Satinder Sartaaj Live",
    about2: "Concerts",
    about3: "",
    lang: ["Punjabi", "Hindi"],
    genre: ["Sufi", "Folk"],
    dates: "Today",
    about:
      "Experience the soulful melodies of Satinder Sartaaj in this intimate live concert. A master of Sufi music and Punjabi poetry, Sartaaj will captivate the audience with his powerful vocals and profound lyrics. The concert will feature a mix of his popular hits and new compositions, promising an evening of musical excellence and spiritual resonance.",
    duration: "3h",
    location: "Siri Fort Auditorium, New Delhi",
    dateRange: "October 5, 2024 - October 5, 2024",
    screeningTypes: ["Live Concert"],
    certification: "U",
    releaseDate: "October 5, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Satinder+Sartaaj",
      "https://via.placeholder.com/120x120.png?text=Accompanying+Musicians",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Sunburn Arena Ft. Boris Brejcha",
    about2: "Concerts",
    about3: "",
    lang: ["English"],
    genre: ["Techno", "Electronic"],
    dates: "Today",
    about:
      "Sunburn Arena presents the 'King of High-Tech Minimal', Boris Brejcha, for an unforgettable night of cutting-edge electronic music. Known for his unique sound and iconic joker mask, Brejcha will take the audience on a journey through his innovative tracks and hypnotic beats. This event promises to be a treat for techno enthusiasts and music lovers alike.",
    duration: "5h",
    location: "India Exposition Mart, Greater Noida",
    dateRange: "November 20, 2024 - November 20, 2024",
    screeningTypes: ["Live DJ Set"],
    certification: "A",
    releaseDate: "November 20, 2024",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Boris+Brejcha",
      "https://via.placeholder.com/120x120.png?text=Supporting+DJ",
    ],
  },
];

export const fun = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Nehru Planetarium, Delhi",
    about2: "Education/Attractions",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Educational", "Science"],
    dates: "Today",
    about:
      "Explore the wonders of the cosmos at the Nehru Planetarium in Delhi. This educational attraction offers immersive shows that take visitors on a journey through space, showcasing the beauty of the night sky and the latest discoveries in astronomy. With state-of-the-art projection technology and expert narration, the planetarium provides an engaging and informative experience for all ages.",
    duration: "1h 30min per show",
    location: "Teen Murti House, New Delhi",
    dateRange: "Open year-round",
    screeningTypes: ["Planetarium Show"],
    certification: "U",
    releaseDate: "Ongoing",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Astronomer",
      "https://via.placeholder.com/120x120.png?text=Narrator",
      "https://via.placeholder.com/120x120.png?text=Educator",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Worlds Of Wonder - Water Park",
    about2: "Amusement Parks",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Water Park", "Family Entertainment"],
    dates: "Today",
    about:
      "Beat the heat at Worlds Of Wonder, one of the largest water parks in Delhi NCR. With a wide array of thrilling water slides, a lazy river, wave pool, and dedicated kids' areas, it offers fun for visitors of all ages. The park also features dry rides, making it a complete family entertainment destination. Enjoy a day of excitement, relaxation, and refreshing aquatic adventures.",
    duration: "Full day activity",
    location: "Sector 38A, Noida",
    dateRange: "Open from March to November",
    screeningTypes: ["Water Park"],
    certification: "U",
    releaseDate: "Seasonal",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Lifeguard",
      "https://via.placeholder.com/120x120.png?text=Ride+Operator",
      "https://via.placeholder.com/120x120.png?text=Park+Mascot",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Atlantic Water World",
    about2: "Amusement Parks",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Water Park", "Family Entertainment"],
    dates: "Today",
    about:
      "Dive into a world of aquatic fun at Atlantic Water World. This expansive water park features a diverse range of attractions including high-speed water slides, a wave pool, and relaxing lagoons. With separate areas for adults and children, it ensures a safe and enjoyable experience for all. The park also offers food courts and lounge areas, making it perfect for a full day of family entertainment.",
    duration: "Full day activity",
    location: "Chhapraula, Uttar Pradesh",
    dateRange: "Open from April to October",
    screeningTypes: ["Water Park"],
    certification: "U",
    releaseDate: "Seasonal",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Lifeguard",
      "https://via.placeholder.com/120x120.png?text=Ride+Operator",
      "https://via.placeholder.com/120x120.png?text=Entertainment+Staff",
    ],
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Museum Of Illusions",
    about2: "Museums",
    about3: "",
    lang: ["Hindi", "English"],
    genre: ["Interactive Museum", "Educational"],
    dates: "Today",
    about:
      "Step into a world where nothing is as it seems at the Museum Of Illusions. This unique attraction challenges your perception and ignites your imagination with a collection of holograms, stereograms, and optical illusions. Interactive exhibits allow visitors to become part of the illusions, creating unforgettable and highly Instagram-able moments. Educational and entertaining, it's a mind-bending experience for visitors of all ages.",
    duration: "1h 30min - 2h",
    location: "Connaught Place, New Delhi",
    dateRange: "Open year-round",
    screeningTypes: ["Interactive Exhibition"],
    certification: "U",
    releaseDate: "Ongoing",
    cast: [
      "https://via.placeholder.com/120x120.png?text=Museum+Guide",
      "https://via.placeholder.com/120x120.png?text=Illusionist",
      "https://via.placeholder.com/120x120.png?text=Photographer",
    ],
  },
];
export const outdoor = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "HUMARE RAM Ft Ashutosh Rana and Rahull R Bhuchar",
    about2: "Theatre",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "HUMARE RAM is a powerful theatrical production featuring acclaimed actors Ashutosh Rana and Rahull R Bhuchar. This thought-provoking play explores the relevance of Lord Ram's teachings in modern society, blending mythology with contemporary issues. Through compelling performances and innovative storytelling, it offers a fresh perspective on age-old wisdom, promising an evening of intellectual stimulation and artistic excellence.",
    duration: "2h 30min",
    location: "Siri Fort Auditorium, New Delhi",
    dateRange: "September 1, 2024 - September 3, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Karan Aujla - It Was All A Dream Delhi NCR",
    about2: "Concerts",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Join Punjabi music sensation Karan Aujla for an electrifying night of music as part of his 'It Was All A Dream' tour. Known for his chart-topping hits and dynamic stage presence, Aujla will perform his popular tracks and latest releases. This high-energy concert promises to be a celebration of contemporary Punjabi music, featuring state-of-the-art production and a stellar live band.",
    duration: "3h",
    location: "Jawaharlal Nehru Stadium, New Delhi",
    dateRange: "October 10, 2024 - October 10, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "ABHIJANANSAKUNTALAM",
    about2: "Theatre",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Experience the timeless Sanskrit classic 'Abhijnanashakuntalam' by Kalidasa in a modern theatrical adaptation. This beautifully crafted production brings to life the love story of Shakuntala and King Dushyanta, exploring themes of love, loss, and destiny. With stunning costumes, emotive performances, and a blend of classical and contemporary theatrical techniques, ABHIJANANSAKUNTALAM offers a mesmerizing journey into ancient Indian literature.",
    duration: "2h 45min",
    location: "Kamani Auditorium, New Delhi",
    dateRange: "November 5, 2024 - November 7, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "ISKATE by Roseate",
    about2: "Sports/Leisure",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Glide into fun at ISKATE by Roseate, India's first all-weather ice skating rink. Whether you're a beginner or an experienced skater, ISKATE offers a unique recreational experience in the heart of Delhi NCR. With state-of-the-art facilities, professional instructors, and a controlled environment, it's the perfect place to beat the heat, learn a new skill, or enjoy a day out with family and friends.",
    duration: "1h sessions available",
    location: "Ambience Mall, Gurugram",
    dateRange: "Open year-round",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "MOHABBAT ZINDABAAD BY JAI SINGH - Delhi NCR",
    about2: "Theatre",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "MOHABBAT ZINDABAAD is a poignant theatrical production that explores the complexities of love in contemporary India. Written and directed by the talented Jai Singh, this play weaves together multiple narratives to create a tapestry of emotions, social commentary, and human connections. With powerful performances and innovative staging, it promises to be a thought-provoking and emotionally resonant experience.",
    duration: "2h 15min",
    location: "Shri Ram Centre for Performing Arts, New Delhi",
    dateRange: "December 1, 2024 - December 3, 2024",
  },
];

export const laughter = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Best of Gupta Ji by Appurv Gupta",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Join comedian Appurv Gupta for an evening of laughter with his show 'Best of Gupta Ji'. Known for his witty observations and relatable humor, Appurv brings his most popular jokes and new material to this special performance. From everyday life situations to social commentary, his comedy spans a wide range of topics, guaranteeing a night full of laughs for audiences of all ages.",
    duration: "1h 30min",
    location: "The Laugh Store, Ambience Mall, Gurugram",
    dateRange: "August 25, 2024 - August 25, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Gaurav Gupta Live - India Tour",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Gaurav Gupta brings his signature style of observational comedy to Delhi NCR as part of his India Tour. With his sharp wit and unique perspective on everyday life, Gaurav tackles everything from relationships to politics, delivering punchlines that resonate with audiences across the country. This show promises an evening of non-stop laughter and insightful humor.",
    duration: "1h 45min",
    location: "Airia Mall, Sector 68, Gurugram",
    dateRange: "September 15, 2024 - September 15, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Gaurav Gupta Live",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Experience the comedic genius of Gaurav Gupta in an intimate setting. This special performance showcases Gaurav's newest material, offering audiences a sneak peek into his creative process. With his trademark blend of self-deprecating humor and social commentary, Gaurav takes on current events, personal anecdotes, and the absurdities of modern life, ensuring an evening of fresh, thought-provoking comedy.",
    duration: "2h",
    location: "Playground Comedy Studio, Sector 29, Gurugram",
    dateRange: "October 5, 2024 - October 5, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Akash Gupta - Delhi NCR",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Rising star of the Indian comedy scene, Akash Gupta, brings his unique brand of humor to Delhi NCR. Known for his hilarious takes on millennial life, relationships, and the quirks of Indian society, Akash's relatable comedy and energetic stage presence promise a night of non-stop laughter. This show features a mix of his popular jokes and fresh material, making it a must-see for both new fans and long-time followers.",
    duration: "1h 30min",
    location: "Studio XO Bar, Sector 29, Gurugram",
    dateRange: "November 10, 2024 - November 10, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Nitin Gupta Rivaldo",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Join Nitin Gupta, better known as Rivaldo, for an evening of intelligent and irreverent comedy. Rivaldo's unique style blends sharp social commentary with absurdist humor, tackling everything from politics to pop culture. His quick wit and unexpected punchlines keep audiences on their toes, making for a comedy experience that's both entertaining and thought-provoking. This show features new material alongside some of Rivaldo's classic bits.",
    duration: "1h 45min",
    location: "Imperfecto Ruin Pub, Sector 29, Gurugram",
    dateRange: "December 20, 2024 - December 20, 2024",
  },
];
export const popular = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "ISKATE by Roseate",
    about2: "Sports/Leisure",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Glide into fun at ISKATE by Roseate, India's first all-weather ice skating rink. Whether you're a beginner or an experienced skater, ISKATE offers a unique recreational experience in the heart of Delhi NCR. With state-of-the-art facilities, professional instructors, and a controlled environment, it's the perfect place to beat the heat, learn a new skill, or enjoy a day out with family and friends.",
    duration: "1h sessions available",
    location: "Ambience Mall, Gurugram",
    dateRange: "Open year-round",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Harley Rock Riders Club Experience - Episode 3",
    about2: "Concerts",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Experience the thrill of rock music and motorcycle culture at the Harley Rock Riders Club Experience - Episode 3. This unique event combines live performances from top rock bands with a showcase of iconic Harley-Davidson motorcycles. Attendees can enjoy electrifying music, explore custom bikes, and immerse themselves in the Harley lifestyle. It's a must-attend for music lovers and motorcycle enthusiasts alike.",
    duration: "6h",
    location: "Backyard Sports Club, Sector 59, Gurugram",
    dateRange: "September 30, 2024 - September 30, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Comedy Night with Vipul Goyal",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Laugh your heart out with Vipul Goyal, one of India's top stand-up comedians. Known for his clean humor and relatable content, Vipul's observational comedy touches on everyday life, relationships, and the quirks of Indian society. This show features a mix of his most popular jokes and fresh material, promising an evening of non-stop laughter and entertainment for audiences of all ages.",
    duration: "1h 30min",
    location: "Carnival Cinemas, Eros One, Jangpura Extension, New Delhi",
    dateRange: "October 15, 2024 - October 15, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Improv Comedy Night with SNG Comedy",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Experience the spontaneous hilarity of improv comedy with SNG Comedy, one of India's premier improv groups. Watch as the talented ensemble creates on-the-spot comedy based on audience suggestions, resulting in a unique and interactive show every time. With their quick wit and chemistry, SNG Comedy promises an evening of unexpected laughs and clever humor that will keep you entertained throughout.",
    duration: "2h",
    location: "The Laugh Store, Vegas Mall, Dwarka, New Delhi",
    dateRange: "November 20, 2024 - November 20, 2024",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Dine in the Dark",
    about2: "Dining Experience",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
    about:
      "Embark on a unique sensory journey with 'Dine in the Dark', an innovative dining experience that challenges your perceptions. Guests are led into a pitch-black dining room where they enjoy a gourmet meal, relying solely on their senses of taste, smell, and touch. This one-of-a-kind event not only offers an exciting culinary adventure but also raises awareness about visual impairment, making for an unforgettable and eye-opening evening.",
    duration: "2h",
    location: "Radisson Blu Plaza Delhi Airport, Mahipalpur, New Delhi",
    dateRange: "Every Saturday and Sunday",
  },
];

export const latest = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "International Yoga Day",
    about2: "Health & Wellness",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Laughathon 2024",
    about2: "Comedy",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Biggest New Year Party 2024",
    about2: "Party",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Fitness Bootcamp",
    about2: "Health & Wellness",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Food Truck Festival",
    about2: "Food & Drink",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
];

export const top = [
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "The Great Indian Musical",
    about2: "Musicals",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Bollywood Extravaganza",
    about2: "Musicals",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Drama Workshop for Kids",
    about2: "Workshops",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Summer Music Festival",
    about2: "Concerts",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
  {
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCAxOCBEZWM%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00405942-skyrkjxxwd-portrait.jpg",
    about1: "Theatre Appreciation Course",
    about2: "Workshops",
    about3: "",
    lang: "Hindi",
    genre: "Action",
    dates: "Today",
  },
];

export const titleList = [
  { title: "Recommended Movies" },
  { title: "Your Music Studio" },
  { title: "Explore Fun Activities" },
  { title: "Outdoor Events" },
  { title: "Laughter Therapy" },
  { title: "Popular Events" },
  { title: "The Latest Plays" },
  { title: "Top Games And Sports Events" },
];

// Page Cmoponnenets

export const Locations = [
  {
    loc: "Delhi",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/ncr.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/ncr-selected.png",
  },
  {
    loc: "Mumbai",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/mumbai.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/mumbai-selected.png",
  },
  {
    loc: "Benagluru",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/bang.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/bang-selected.png",
  },
  {
    loc: "Ahemdabad",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/ahd.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/ahd-selected.png",
  },
  {
    loc: "Hyderabad",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/hyd.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/hyd-selected.png",
  },
  {
    loc: "Chandhigarh",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/chd.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/chd-selected.png",
  },
  {
    loc: "Pune",
    src: "	https://in.bmscdn.com/m6/images/common-modules/regions/pune.png",
    srcSelected:
      "	https://in.bmscdn.com/m6/images/common-modules/regions/pune-selected.png",
  },
  {
    loc: "Chennai",
    src: "	https://in.bmscdn.com/m6/images/common-modules/regions/chen.png",
    srcSelected:
      "	https://in.bmscdn.com/m6/images/common-modules/regions/chen-selected.png",
  },
  {
    loc: "Kochi",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/koch.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/koch-selected.png",
  },
  {
    loc: "Kolkata",
    src: "https://in.bmscdn.com/m6/images/common-modules/regions/kolk.png",
    srcSelected:
      "https://in.bmscdn.com/m6/images/common-modules/regions/koch-selected.png",
  },
];

export const navElements = [
  { to: "/movies", title: "Movies" },
  { to: "/events", title: "Events" },
  { to: "/plays", title: "Plays" },
  { to: "/sports", title: "Sports" },
  { to: "/activities", title: "Activities" },
];

export const navElements2 = [
  { to: "/listyourshow", title: "ListYourShow" },
  { to: "/giftcards", title: "Gift Cards" },
];

export const Trendingbox = [
  { about1: "Despicable Me 4", about2: "Movies" },
  { about1: "Deadpool & Wolverine", about2: "Movies" },
  { about1: "Karan Aujhla - It Was All A Dream", about2: "Events" },
  { about1: "Sunburn Arena feat. Alan Walker", about2: "Events" },
  { about1: "Kalki 2898D", about2: "Movies" },
  { about1: "Dhanji-BARGAM Tour", about2: "Events" },
  { about1: "Kill", about2: "Movies" },
  { about1: "Despicable Me 4", about2: "Movies" },
  { about1: "Deadpool & Wolverine", about2: "Movies" },
  { about1: "Sarfira", about2: "Movies" },
];

// sidebar

export const Sidebarel = [
  {
    src: "https://cdn-icons-png.freepik.com/256/8276/8276934.png?semt=ais_hybrid",
    about1: "Notifications",
    about2: "",
  },
  {
    src: "https://assets-in.bmscdn.com/members/common/icons/purchasehistory.png",

    about1: "Your Orders",
    about2: "View all your Bookings & purchases",
  },
  {
    src: "https://assets-in.bmscdn.com/members/common/icons/streamlibrary_2.png",
    about1: "Stream Library",
    about2: "Rented Purchases & Movies",
  },
  {
    src: "https://assets-in.bmscdn.com/members/common/icons/playcreditcard.png",
    about1: "Play Credit Card",
    about2: "View your Play credut card details & offers",
  },
  {
    src: "https://assets-in.bmscdn.com/members/common/icons/helpandsupport.png",
    about1: "Help & support",
    about2: "View Commonly asked queries & chat",
  },
  {
    src: "https://assets-in.bmscdn.com/members/common/icons/accountandsettings.png",
    about1: "Account & Settings",
    about2: "Locations, Permissions, Payments & More",
  },
  {
    src: "https://assets-in.bmscdn.com/members/common/icons/rewards_1.png",
    about1: "Rewards",
    about2: "View Your Awards & unlock new ones",
  },
  {
    src: "https://cdn-icons-png.flaticon.com/128/569/569501.png",
    about1: "GetASmile",
    about2: "",
  },
];

// Filters

export const movieLanguage = [
  "Hindi",
  "English",
  "Punjabi",
  "Gujrati",
  "Korean",
  "Assamese",
  "Multi Language",
  "Tamil",
  "Kannada",
];
export const movieGenre = [
  "Drama",
  "Comedy",
  "Action",
  "Animation",
  "Fantasy",
  "Crime",
  "Horror",
];

export const sportCategories = [
  "Running",
  "Bowling",
  "Football",
  "Bowling",
  "Cycling",
  "Cricket",
  "Walking",
  "Online Games",
  "Online Sports",
];

export const format = [
  "2D",
  "3D",
  "4DX 3D",
  "3D SCREEN X",
  "IMAX 3D",
  "ICE",
  "ICE 3D",
];
export const eventLanguages = [
  "English",
  "Hindi",
  "Marathi",
  "Tamil",
  "Bengali",
  "Telugu",
  "Kannada",
  "Gujarati",
  "Malayalam",
  "Urdu",
  "Punjabi",
  "Sanskrit",
  "Hinglish",
  "French",
  "Korean",
  "Marwadi",
  "Odia",
  "Rajasthani",
  "Sindhi",
];
export const eventCategories = [
  "Comedy Shows",
  "Workshops",
  "Music Shows",
  "Performances",
  "Kids",
  "Meetups",
  "Exhibitions",
  "Conferences",
  "Screening",
  "Talks",
  "Spirituality",
];
export const activitiesCategories = [
  "Adventure",
  "Unique Tours",
  "Amusement Parks",
  "Gaming",
  "Antiques, Heritage, Museums",
  "Tourist Attractions",
  "Food and Drinks",
  "Festivals",
  "Nightlife",
  "Navratri Celebration",
  "Parties",
  "Quizzes and Competitions",
];
export const otherCat = [
  "Outdoor Events",
  "Fast Filling",
  "Kids Allowed",
  "Kids Activities",
  "Weekend Getaway",
  "Challenges",
  "Must Attend",
  "Online Streaming",
  "Spiritual Tourism",
  "Stay Packages",
  "Unmissable Events",
];
export const playsCategouries = ["Theatre", "Storytelling", "Monologue"];
export const playsGenre = [
  "Drama",
  "Comedy",
  "Musical",
  "Contemporary",
  "Romantic",
  "Suspense",
  "Mythological",
  "Classic",
  "Historical",
  "Thriller",
  "Adaptation",
  "Adventure",
  "Biography",
  "Period",
  "Regional",
  "Adult",
  "Fantasy",
  "Horror",
  "Mystery",
  "Psychological",
  "Sci-Fi",
  "Tribute",
];
export const playsFiltes = ["Theatre", "Storytelling", "Monologue"];
export const price = ["0-500", "500-1500", "1500-3000", "1000-5000"];
export const dates = ["Today", "Tommorow", "This Weekend"];

// temp

export const lang = [
  "Hindi",
  "English",
  "Punjabi",
  "Gujrati",
  "Korean",
  "Assamese",
  "Multi Language",
  "Tamil",
  "Kannada",
];
export const genre = [
  "Drama",
  "Comedy",
  "Action",
  "Animation",
  "Fantasy",
  "Crime",
  "Horror",
];

export const filters = ["Languages", "Genre", "Format"];

export const ShowList1 = [
  {
    id: 1,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/perf.png" },
      { head: "Performances" },
      { head2: "Get everything from a music gig to a theatrical performance." },
      {
        src2: "https://assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png",
      },
      { src3: "//assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png" },
    ],
  },
  {
    id: 2,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/experiencess.png" },
      { head: "Experiences" },
      {
        head2:
          "Got an experience to share? List your brunches, dinners, walking tours, activities...",
      },
      {
        src2: "https://assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png",
      },
      { src3: "//assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png" },
    ],
  },
  {
    id: 3,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/expositionss.png" },
      { head: "Expositions" },
      {
        head2:
          "Maximise the attendees at your exhibitions, trade fairs, and more",
      },
      {
        src2: "https://assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png",
      },
      { src3: "//assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png" },
    ],
  },
  {
    id: 4,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/partiess.png" },
      { head: "Parties" },
      {
        head2:
          "From NYE to Christmas, host insane parties for various occasions at your venue",
      },
      {
        src2: "https://assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png",
      },
      { src3: "//assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png" },
    ],
  },
  {
    id: 5,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/sport.png" },
      { head: "Sports" },
      {
        head2:
          "Cricket, football, or marathons, host your sporting and gaming events with us",
      },
      {
        src2: "https://assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png",
      },
      { src3: "//assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png" },
    ],
  },
  {
    id: 6,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/conferencess.png" },
      { head: "Conferences" },
      {
        head2:
          "Dare to make a difference with your meetings and conferences? Make your voice heard",
      },
      {
        src2: "https://assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png",
      },
      { src3: "//assets-in.bmscdn.com/m6/list-your-show/hi-4-card11.png" },
    ],
  },
];
export const ShowList2 = [
  {
    id: 1,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/online-saless.png" },
      { head: "Online Sales & Marketing" },
      { head2: "Details about online sales and marketing management." },
      {
        src2: "https://assets-in.bmscdn.com/static/2021/06/online-saless.png",
      },
      { src3: "//assets-in.bmscdn.com/static/2021/06/online-saless.png" },
    ],
    featlist: [
      { f: "Target millions of potential customers" },
      { f: "Hassle free sales" },
      { f: "Create custom discounts" },
      { f: "Engage on social media" },
      { f: "Sell more tickets on ground" },
    ],
  },
  {
    id: 2,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/pricings.png" },
      { head: "Pricing" },
      { head2: "Insights into pricing strategies and management." },
      {
        src2: "https://assets-in.bmscdn.com/static/2021/06/pricings.png",
      },
      { src3: "//assets-in.bmscdn.com/static/2021/06/pricings.png" },
    ],
    featlist: [
      { f: "Pricing recommendations" },
      { f: "Hassle free sales" },
      { f: "Budget promotional spends" },
      { f: "Change ticket price dynamically" },
      { f: "Fast tacked payment reconciliation" },
    ],
  },
  {
    id: 3,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/food.png" },
      { head: "Food & Beverages, stalls and the works" },
      { head2: "Manage food stalls, beverages, and other related services." },
      {
        src2: "https://assets-in.bmscdn.com/static/2021/06/food.png",
      },
      { src3: "//assets-in.bmscdn.com/static/2021/06/food.png" },
    ],
    featlist: [
      { f: "Cashless payments" },
      { f: "Age verification counters" },
      { f: "Offer sponsor discounts" },
      { f: "Engage on social media" },
      { f: "Ticket specific offerings" },
    ],
  },
  {
    id: 4,
    dat: [
      {
        src1: "https://assets-in.bmscdn.com/static/2021/06/on-ground-support.png",
      },
      { head: "On ground support & gate entry management" },
      {
        head2: "Oversee on-ground support and gate entry management.",
      },
      {
        src2: "https://assets-in.bmscdn.com/static/2021/06/on-ground-support.png",
      },
      {
        src3: "//assets-in.bmscdn.com/static/2021/06/on-ground-support.png",
      },
    ],
    featlist: [
      { f: "Stage setup" },
      { f: "logistics and handling" },
      { f: "Box office support" },
      { f: "Accreditation for your team" },
      { f: "And so on..." },
    ],
  },
  {
    id: 5,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/report.png" },
      { head: "Reports & business insights" },
      {
        head2: "Generate and analyze reports for business insights.",
      },
      {
        src2: "https://assets-in.bmscdn.com/static/2021/06/report.png",
      },
      { src3: "//assets-in.bmscdn.com/static/2021/06/report.png" },
    ],
    featlist: [
      { f: "In depth reports" },
      { f: "Access registration data" },
      { f: "behavioural insights" },
    ],
  },
  {
    id: 6,
    dat: [
      { src1: "https://assets-in.bmscdn.com/static/2021/06/rfids.png" },
      { head: "POS, RFID, Turnstiles & more..." },
      {
        head2:
          "Handle POS, RFID systems, turnstiles, and related technologies.",
      },
      {
        src2: "https://assets-in.bmscdn.com/static/2021/06/rfids.png",
      },
      { src3: "//assets-in.bmscdn.com/static/2021/06/rfids.png" },
    ],
    featlist: [
      { f: "Digital tickets" },
      { f: "Print at Home ticket solution" },
      { f: "Mobile ticket scanning" },
      { f: "We can go on...." },
    ],
  },
];

export const GiftImglist = [
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+1",
    combo: "Combo1",
    cprice: " ₹2000",
    card1: "Card1",
    C1price: " ₹1000",
    card2: "Card2",
    C2price: " ₹1000",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+2",
    combo: "Combo2",
    cprice: " ₹2100",
    card1: "Card2",
    C1price: " ₹1050",
    card2: "Card3",
    C2price: " ₹1050",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+3",
    combo: "Card3",
    cprice: " ₹1000",
    card1: "Card3",
    C1price: " ₹1000",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+4",
    combo: "Combo4",
    cprice: " ₹3000",
    card1: "Card4",
    C1price: " ₹1500",
    card2: "Card5",
    C2price: " ₹1500",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+5",
    combo: "Card5",
    cprice: " ₹1200",
    card1: "Card5",
    C1price: " ₹1200",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+6",
    combo: "Combo6",
    cprice: " ₹2500",
    card1: "Card6",
    C1price: " ₹1250",
    card2: "Card7",
    C2price: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+7",
    combo: "Card7",
    cprice: " ₹1100",
    card1: "Card7",
    C1price: " ₹1100",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+8",
    combo: "Combo8",
    cprice: " ₹2200",
    card1: "Card8",
    C1price: " ₹1100",
    card2: "Card9",
    C2price: " ₹1100",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+9",
    combo: "Card9",
    cprice: " ₹1150",
    card1: "Card9",
    C1price: " ₹1150",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+10",
    combo: "Combo10",
    cprice: " ₹2500",
    card1: "Card10",
    C1price: " ₹1250",
    card2: "Card11",
    C2price: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+11",
    combo: "Card11",
    cprice: " ₹1300",
    card1: "Card11",
    C1price: " ₹1300",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+12",
    combo: "Card12",
    cprice: " ₹1350",
    card1: "Card12",
    C1price: " ₹1350",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+13",
    combo: "Combo13",
    cprice: " ₹2700",
    card1: "Card13",
    C1price: " ₹1350",
    card2: "Card14",
    C2price: " ₹1350",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+14",
    combo: "Combo14",
    cprice: " ₹2200",
    card1: "Card14",
    C1price: " ₹1100",
    card2: "Card15",
    C2price: " ₹1100",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+15",
    combo: "Card15",
    cprice: " ₹1200",
    card1: "Card15",
    C1price: " ₹1200",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+16",
    combo: "Card16",
    cprice: " ₹1250",
    card1: "Card16",
    C1price: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+17",
    combo: "Combo17",
    cprice: " ₹2600",
    card1: "Card17",
    C1price: " ₹1300",
    card2: "Card18",
    C2price: " ₹1300",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+18",
    combo: "Card18",
    cprice: " ₹1350",
    card1: "Card18",
    C1price: " ₹1350",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+19",
    combo: "Combo19",
    cprice: " ₹2100",
    card1: "Card19",
    C1price: " ₹1050",
    card2: "Card20",
    C2price: " ₹1050",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+20",
    combo: "Card20",
    cprice: " ₹1100",
    card1: "Card20",
    C1price: " ₹1100",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+21",
    combo: "Combo21",
    cprice: " ₹2400",
    card1: "Card21",
    C1price: " ₹1200",
    card2: "Card22",
    C2price: " ₹1200",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+22",
    combo: "Card22",
    cprice: " ₹1250",
    card1: "Card22",
    C1price: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+23",
    combo: "Combo23",
    cprice: " ₹2300",
    card1: "Card23",
    C1price: " ₹1150",
    card2: "Card24",
    C2price: " ₹1150",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+24",
    combo: "Card24",
    cprice: " ₹1200",
    card1: "Card24",
    C1price: " ₹1200",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+25",
    combo: "Combo25",
    cprice: " ₹2300",
    card1: "Card25",
    C1price: " ₹1150",
    card2: "Card26",
    C2price: " ₹1150",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+26",
    combo: "Card26",
    cprice: " ₹1200",
    card1: "Card26",
    C1price: " ₹1200",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+27",
    combo: "Combo27",
    cprice: " ₹2200",
    card1: "Card27",
    C1price: " ₹1100",
    card2: "Card28",
    C2price: " ₹1100",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+28",
    combo: "Card28",
    cprice: " ₹1150",
    card1: "Card28",
    C1price: " ₹1150",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+29",
    combo: "Combo29",
    cprice: " ₹2500",
    card1: "Card29",
    C1price: " ₹1250",
    card2: "Card30",
    C2price: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+30",
    combo: "Card30",
    cprice: " ₹1300",
    card1: "Card30",
    C1price: " ₹1300",
  },

  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+31",
    combo: "Combo31",
    cprice: " ₹2400",
    card1: "Card31",
    C1price: " ₹1200",
    card2: "Card32",
    C2price: " ₹1200",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+32",
    card1: "Card32",
    cprice: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+33",
    card1: "Card33",
    cprice: " ₹1300",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+34",
    combo: "Combo34",
    cprice: " ₹2500",
    card1: "Card34",
    C1price: " ₹1250",
    card2: "Card35",
    C2price: " ₹1250",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+35",
    card1: "Card35",
    cprice: " ₹1300",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+36",
    combo: "Combo36",
    cprice: " ₹2600",
    card1: "Card36",
    C1price: " ₹1300",
    card2: "Card37",
    C2price: " ₹1300",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+37",
    card1: "Card37",
    cprice: " ₹1350",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+38",
    card1: "Card38",
    cprice: " ₹1400",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+39",
    combo: "Combo39",
    cprice: " ₹2700",
    card1: "Card39",
    C1price: " ₹1350",
    card2: "Card40",
    C2price: " ₹1350",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+40",
    card1: "Card40",
    cprice: " ₹1400",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+41",
    combo: "Combo41",
    cprice: " ₹2800",
    card1: "Card41",
    C1price: " ₹1400",
    card2: "Card42",
    C2price: " ₹1400",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+42",
    card1: "Card42",
    cprice: " ₹1450",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+43",
    combo: "Combo43",
    cprice: " ₹2900",
    card1: "Card43",
    C1price: " ₹1450",
    card2: "Card44",
    C2price: " ₹1450",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+44",
    card1: "Card44",
    cprice: " ₹1500",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+45",
    combo: "Combo45",
    cprice: " ₹3000",
    card1: "Card45",
    C1price: " ₹1500",
    card2: "Card46",
    C2price: " ₹1500",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+46",
    card1: "Card46",
    cprice: " ₹1550",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+47",
    combo: "Combo47",
    cprice: " ₹3100",
    card1: "Card47",
    C1price: " ₹1550",
    card2: "Card48",
    C2price: " ₹1550",
  },
  {
    src: "https://via.placeholder.com/286x184.png?text=Gift+Card+48",
    card1: "Card48",
    cprice: " ₹1600",
  },
];
